name: Symfony 5 Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  symfony:
    name: Tests
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: elecomp
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - uses: actions/checkout@v2
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - uses: php-actions/composer@v5 # or alternative dependency management
      - uses: php-actions/phpunit@v3