name: Symfony 5 Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  symfony:
    name: Tests
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE